export default {
    show_transactions_navbar: "#tabs > ul > li:nth-child(1)",
    find_transactions_navbar: "#tabs > ul > li:nth-child(2)",
    board_header: ".board-header",
    board_header2: "#ui-tabs-2 > h2",
    desc: "#ui-tabs-1 > p > i",
    desc2: "#ui-tabs-2 > p > i",
    savings_date_1: "#all_transactions_for_account > table > tbody > tr:nth-child(1) > td:nth-child(1)",
    savings_date_2: "#all_transactions_for_account > table > tbody > tr:nth-child(2) > td:nth-child(1)",
    savings_date_3: "#all_transactions_for_account > table > tbody > tr:nth-child(3) > td:nth-child(1)",
    savings_desc_1: "#all_transactions_for_account > table > tbody > tr:nth-child(1) > td:nth-child(2)",
    savings_desc_2: "#all_transactions_for_account > table > tbody > tr:nth-child(2) > td:nth-child(2)",
    savings_desc_3: "#all_transactions_for_account > table > tbody > tr:nth-child(3) > td:nth-child(2)",
    savings_deposit_1: "#all_transactions_for_account > table > tbody > tr:nth-child(1) > td:nth-child(3)",
    savings_deposit_2: "#all_transactions_for_account > table > tbody > tr:nth-child(2) > td:nth-child(3)",
    savings_deposit_3: "#all_transactions_for_account > table > tbody > tr:nth-child(3) > td:nth-child(3)",
    savings_withdrawal_1: "#all_transactions_for_account > table > tbody > tr:nth-child(1) > td:nth-child(4)",
    savings_withdrawal_2: "#all_transactions_for_account > table > tbody > tr:nth-child(2) > td:nth-child(4)",
    savings_withdrawal_3: "#all_transactions_for_account > table > tbody > tr:nth-child(3) > td:nth-child(4)",
    savings_price_1: "#all_transactions_for_account > table > tbody > tr:nth-child(1) > td:nth-child(3)",
    savings_price_2: "#all_transactions_for_account > table > tbody > tr:nth-child(2) > td:nth-child(4)",
    savings_price_3: "#all_transactions_for_account > table > tbody > tr:nth-child(3) > td:nth-child(3)",
    aa_fromDate: "#aa_fromDate",
    aa_toDate: "#aa_toDate",
    submit_button: 'button[type="submit"]',
    all_transactions_for_account: "#all_transactions_for_account",
    aa_accountId: "#aa_accountId",
}